version: '3.1'

services:

  itware-db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3338:3306
    environment:
      # Use root as user
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "itware"
      MYSQL_USER: "itware"
      MYSQL_PASSWORD: "password"

  itware-redis:
    image: redis:6.0.8-alpine
    restart: always
    ports:
      - 6379:6379
#    environment:
#      - REDIS_REPLICATION_MODE=master
#    volumes:
#       - $PWD/redis-data:/var/lib/redis
#       - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
